### PR TITLE
Migrate sandbox from uber/michelangeo to michelangelo-ai/michelangelo

### PR DESCRIPTION
**Pull request by sallycr**
Migrate sandbox script to new open source repo.

### CODE REVIEW

**Review by mincai — APPROVED** [review]

**Comment by mincai** [comment]
We might want to rename sandbox and move to a different directory. But we can make the changes separately.

**Comment by andriika** [comment]
How do users use it outside of this monorepo?

**Comment by sallycr** [comment]
> We might want to rename sandbox and move to a different directory. But we can make the changes separately.

any alternative way do you want to propose? I browse many others and everyone has own way. but I like the approach of 'mactl demo start' in flytectl does or mlflow does 'mlflow server ...'

**Comment by sallycr** [comment]
> How do users use it outside of this monorepo?

That should be the nexts step. And outside of this monorepo should use APIs. For SDK path, we need to design.

**Pull request merged**
